openapi: "3.0.2"
info:
  title: Task tracker application
  version: "1.0"
servers:
  - url: /api
paths:
  /tasks:
    get:
      operationId: listTasks
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"

components:
  schemas:
    Todo:
      properties:
        title:
          type: string
        status:
          enum:
            - TODO
            - DOING
            - DONE
      required:
        - title
        - status
