openapi: 3.0.3
info:
  title: The task application
  description: A task list for adding, listing and completing tasks
  version: 1.0.0
servers:
  - url: /api
    description: current
paths:
  /login:
    get:
      tags: [ Login ]
      operationId: getUserProfile
      responses:
        200:
          description: Show the current user information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        401:
          description: User is not logged in
  /login/start:
    get:
      tags: [ Login ]
      operationId: startLogin
      responses:
        307:
          description: Redirection to identity provider
          headers:
            location:
              description: Idenity provider authorization uri
              schema:
                type: string
                format: uri
  /todos:
    get:
      tags: [ Todos ]
      operationId: listTodos
      responses:
        200:
          description: Show a list of all the tasks available to the current user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TodoSnapshot"
    post:
      tags: [ Todos ]
      operationId: createTodo
      requestBody:
        description: The task to be created
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Todo"
      responses:
        204:
          description: Task was created
  /todos/updateState:
    post:
      tags: [Todos]
      operationId: updateTodoState
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                state:
                  $ref: "#/components/schemas/TodoState"
                idList:
                  type: array
                  items:
                    type: string
                    format: uuid
              required:
                - state
                - idList
      responses:
        204:
          description: Updated
        403:
          description: You tried to update a todo that you do not own
  /todos/{id}:
    put:
      tags: [ Todos ]
      operationId: updateTodo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoProperties"
      responses:
        204:
          description: Update was successful
        403:
          description: This is not your task
components:
  schemas:
    TodoProperties:
      properties:
        title:
          type: string
        state:
          $ref: "#/components/schemas/TodoState"
        description:
          type: string

    TodoState:
      enum:
        - WAITING
        - DOING
        - DONE

    Todo:
      allOf:
        - $ref: "#/components/schemas/TodoProperties"
        - properties:
            id:
              type: string
              format: uuid
      required:
        - id
        - title
        - state

    TodoSnapshot:
      allOf:
        - $ref: "#/components/schemas/ChangeTracked"
        - $ref: "#/components/schemas/Todo"

    UserProfile:
      properties:
        username:
          type: string
        displayName:
          type: string
        emailAddress:
          type: string
          format: email
      required:
        - username

    ChangeTracked:
      properties:
        createdBy:
          type: string
          format: username
        createdAt:
          type: string
          format: date-time
        updatedBy:
          type: string
          format: username
        updatedAt:
          type: string
          format: date-time
      required:
        - createdAt
        - createdBy
        - updatedAt
        - updatedBy