openapi: "3.0.2"
info:
  title: Task tracker application
  version: "1.0"
servers:
  - url: /api
paths:
  /tasks:
    get:
      operationId: listTasks
      tags: [ Tasks ]
      responses:
        200:
          description: Lists all tasks visible to current user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
  /tasks/{id}:
    put:
      operationId: updateTaskStatus
      tags: [ Tasks ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              properties:
                status:
                  $ref: "#/components/schemas/TaskStatus"
      responses:
        204:
          description: Task was updated
        400:
          description: Invalid change
        401:
          description: Unauthorized user
        404:
          description: Non-existent task
  /login:
    get:
      operationId: getUserinfo
      tags: [ Login ]
      responses:
        200:
          description: Shows information about the currently logged in user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Userinfo"
        401:
          description: User is not logged in

components:
  schemas:
    Todo:
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        status:
          $ref: "#/components/schemas/TaskStatus"
      required:
        - id
        - title
        - status
    Userinfo:
      properties:
        displayName:
          type: string
        uniqueName:
          type: string
          format: email
    TaskStatus:
      enum:
        - TODO
        - DOING
        - DONE
