openapi: 3.0.3
info:
  title: The task application
  description: A task list for adding, listing and completing tasks
  version: 1.0.0
servers:
  - url: /api
    description: current
paths:
  /todos:
    get:
      tags: [Todos]
      operationId: listTodos
      responses:
        200:
          description: Show a list of all the tasks available to the current user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
    post:
      tags: [Todos]
      operationId: createTodo
      requestBody:
        description: The task to be created
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Todo"
      responses:
        204:
          description: Task was created
components:
  schemas:
    Todo:
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        state:
          enum:
            - WAITING
            - DOING
            - DONE
        description:
          type: string
      required:
        - id
        - title
        - state
