apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}{{ .Values.suffix }}
spec:
  selector:
    app: {{ .Values.appName }}{{ .Values.suffix }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
